sudo: required
language: cpp
branches:
 only:
 - master

addons:
  apt:
    packages:
      - gfortran
      - binutils
      - cmake
      - g++
      - python-pip

env: FC=gfortran

matrix:
  include:
  - os: osx
  - os: linux
  - os: windows
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install g++ cmake; fi
script: 
 - mkdir build
 - cd build
 - cmake ..
 - cp ../test/run.sh .
 - bash run.sh


