sudo: required
language: bash
branches:
 only:
 - master

matrix:
  include:
  - os: osx
    addons:
      apt:
        packages:
          - gfortran
          - binutils
          - cmake
          - make
          - g++
          - python-pip
    script: 
       - mkdir build && cd build
       - cmake ..  && make
       - cp ../test/run.sh . &&  bash run.sh
  - os: linux
    addons:
      apt:
        packages:
          - gfortran
          - binutils
          - cmake
          - make
          - g++
          - python-pip
    install:
      - if [ $travis_os_name = linux ]; then sudo apt-get install g++ cmake; fi
    script: 
       - mkdir build && cd build
       - cmake ..  && make
       - cp ../test/run.sh . &&  bash run.sh



