sudo: false
language: cpp
compiler: gcc
branches:
 only:
 - master
os: 
  - osx
  - linux
before_install:
  - bash "echo  'Using OS: $TRAVIS_OS_NAME'"
script: 
 - make library && make test
 - make run_test

