sudo: false
language: cpp
compiler: gcc
branches:
 only:
 - master
os: 
  - osx
  - linux
matrix:
 include:
  - os: osx
    env:
	  - MATRIX_EVAL="MacOS gcc"
  - os: linux
    env:
	  - MATRIX_EVAL="Linux gcc"
before_install:
  - eval "${MATRIX_EVAL}"
script: 
 - make library && make test
 - make run_test

