sudo: true
language: cpp
branches:
 only:
 - master

addons:
  apt:
    packages:
      - gfortran
      - binutils
      - cmake
      - g++
      - python-pip

env: FC=gfortran

matrix:
  include:
  - os: osx
     language: sh
  - os: linux
     language: sh
  - os: windows
     language: sh
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install g++ cmake; fi
script: 
 - make library && make test
 - make run_test

