sudo: false
language: cpp
branches:
 only:
 - master
matrix:
  include:
  - os: 
     osx
  - os: 
     linux
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install g++ cmake; fi
script: 
 - make library && make test
 - make run_test

